### ISSUE TITLE
feat: findAll payments

### ISSUE THREAD

**Issue by kimseungbin** [HPlus1100/server#40]
# Description

- Payments service test boilerplate 작성
- findAll method test 구현

# Todos

- [x] generate payments resources using nest cli
- [x] add todos for payments controller
- [x] add todos for payments service
- [x] implement findAll payments method test
